name: MythicLib
author: Indyuce
main: io.lumine.mythic.lib.MythicLib
api-version: 1.14
version: ${project.version}
description: ${project.description}
website: www.phoenixdevt.fr
softdepend: [ WorldGuard,Residence,Factions,MythicMobs,PlaceholderAPI ]
commands:
  healthscale:
    description: 'No longer maintained, see ''/ml debug healthscale'' instead'
    permission: mythiclib.command.healthscale
  mmotempstat:
    description: 'No longer maintained, see ''/ml tempstat'' instead'
    permission: mythiclib.tempstat
  superworkbench:
    aliases: [ swb ]
    description: Open the super 5x5 workbench
    permission: mythiclib.superworkbench
  megaworkbench:
    aliases: [ mwb ]
    description: Open the mega 6x6 workbench
    permission: mythiclib.megaworkbench
permissions:
  mythiclib.admin:
    default: op
  mythiclib.mythiclib.command.healthscale:
    default: op
  mythiclib.tempstat:
    default: op
  mythiclib.superworkbench:
    default: op
  mythiclib.megaworkbench:
    default: op
